# Generated by Django 4.2.6 on 2023-10-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Текст'),
        ),
    ]
